### ISSUE TITLE
PDF background color cannot follow with that of the Jetbrains

### ISSUE THREAD

**Issue by waltertan1988** [FirstTimeInForever/intellij-pdf-viewer#103]
It would be better if the open PDF background color is the same as that color of Jebrains product (like IDEA, WebStorm)

**Comment by PHPirates** [comment]
There is a button "set current theme colors" in settings, is that what you mean? 

![image](https://github.com/FirstTimeInForever/intellij-pdf-viewer/assets/15669080/13049be6-eab1-4be5-ae09-0831952d2ba5)
