### ISSUE TITLE
feature request: option to render pdf with pdfium (chromium's pdf)

### ISSUE THREAD

**Issue by liudongmiao** [FirstTimeInForever/intellij-pdf-viewer#113]
https://plugins.jetbrains.com/docs/intellij/jcef.html

JCEF (Java Chromium Embedded Framework) is a Java port of [CEF](https://bitbucket.org/chromiumembedded/cef/wiki/Home). It allows for embedding [Chromium-based browsers](https://www.chromium.org/Home) in Swing applications.

As embedding chromium support pdf, I think an option to render pdf with pdfium is acceptable.

However, I don't find api for pdfium to work with synctex.

**Comment by liudongmiao** [comment]
pdfium is very easy, we can just response the pdf file, that's so easy. (I have tested.)

the way use pdf.js is very hard to update. I need to change index.html and ViewerConfiguration.ts.
And higher version doesn't expose AppOptions...

**Comment by PHPirates** [comment]
That's true, in #102 I noticed some issues when trying to update pdfjs that I have not been able to fix yet.
However, pdfium is written in c++? Would we need java bindings?

**Comment by liudongmiao** [comment]
@PHPirates it seems there is no public api for pdfium. An option for pdfium make it possible to show the rendered pdf in chrome.

For pdf.js, overleaf use pdf.js too, which use almost the latest version 4.5.136 (pdfjsLib.version in console), and overleaf use pdfjsViewer, not the viewer.js in firefox and this plugin. After some patch, I can update the pdf.js to 3.3.122, and it works. (3.4 and 3.5 use wrong name in lib/web/app.js, 3.6+ has no lib/web/app.js anymore.)

**Comment by PHPirates** [comment]
I see, then it might indeed be a problem to implement synctex support.

Hm, could we use pdfjsViewer in this plugin as well?
Yeah I don't know if you saw but https://github.com/mozilla/pdf.js/pull/16350 explains why they don't want people to use lib/, however it is not clear to me what we should use instead.

**Comment by liudongmiao** [comment]
@PHPirates I have update pdfjs to latest: https://github.com/liudongmiao/intellij-pdf-viewer/commits/pdfjs/

In short, the lib in pdf.js is build with some option, then I just build it again from pdf.js source code with some options.

Not work: go to next page / previous page

And it should be easy if we change webpack to gulp like pdf.js.

**Comment by PHPirates** [comment]
I don't know, why would it be simpler to use gulp instead of a webpack config? I don't know gulp, it seems to be a task runner?

**Comment by liudongmiao** [comment]
@PHPirates Just implement a simple way to render pdf in jcef, please see #117
