### ISSUE TITLE
Shortcut for focusing search-field

### ISSUE THREAD

**Issue by thomasjahoda** [FirstTimeInForever/intellij-pdf-viewer#16]
In normal files you can open or switch focus to the search field with the shortcut Ctrl+F. A lot of people are used to this shortcut working kind of everywhere.

(Otherwise, thank you for providing this plugin. I wrote a positive review.)

**Comment by FirstTimeInForever** [comment]
Actually, you can already do `Ctrl+F` to focus viewer's search field. You might need to manually set the shortcut for this action, though (open keymap settings and search for `Plugins > PDF Viewer > Find In Document`), as I recently discovered some of my shortcuts are broken on platforms other than OSX. Please let me know if this helps.

**Comment by thomasjahoda** [comment]
@FirstTimeInForever Thank you for your answer. I fixed the shortcut for me manually. Default shortcut on Linux&Windows should be Ctrl+F. In fact no shortcut should include Meta on those platforms.
However I've observed one bug: the shortcut does not focus the search field like it would when I click on it. E.g. Ctrl+a should select all the current search field's content, but instead it selects the whole PDF content as if the focus is not on the search field.

**Comment by FirstTimeInForever** [comment]
Sorry for the late response. It seems that there is still a bug with JCEF that prevents transferring keyboard focus to other components. I'll try to find a workaround in the next major release, but can't promise much as this is not even an IDEA bug (as JCEF is in JBR). 
In the mean time, I pushed the new minor version, which should fix default shortcuts for Linux and Windows.

**Comment by thomasjahoda** [comment]
Unrelated: @FirstTimeInForever I think you are pushing yourself too hard for this **free** plugin^^ You owe noone to answer issues quickly or to search for workarounds for bugs which are not even in your code and will be probably be fixed in the future anyhow. But thanks for your efforts :)

**Comment by PHPirates** [comment]
Both Ctrl+F and Ctrl+F, Ctrl+A are working fine for me now.
