### ISSUE TITLE
View is not available until indexes are rebuilt

### ISSUE THREAD

**Issue by breandan** [FirstTimeInForever/intellij-pdf-viewer#17]
Tried viewing a PDF while the IDE was indexing, but was unable to see its contents. Why does viewing a PDF require an index?

![pdf_viewer](https://user-images.githubusercontent.com/175716/106783378-3edfc500-6619-11eb-84b0-a50d03142645.png)

**Comment by FirstTimeInForever** [comment]
Thank you for noticing! The fix is on the way (will be available on Monday or Tuesday).

**Comment by FirstTimeInForever** [comment]
Should be fixed in `0.10.1`.
