### ISSUE TITLE
Filesystem links aren't followed

### ISSUE THREAD

**Issue by chrisvelevitch** [FirstTimeInForever/intellij-pdf-viewer#19]
I'm running Intellij 2020.3.2 on MacOS 11.14.6 and I created aliases for the pdf files I want to view in my project and I've created a docs folder in my project and copied the aliases into that folder.

When I try to view these pdf files, I get:-
```
PDF.js v2.2.171 (build: c8c937c2)
Message: Invalid PDF structure
undefined
```
I was hoping not to create copies of the same pdf files in each project I need them in.

**Comment by PHPirates** [comment]
`ln -s main.pdf main-2.pdf` and opening the link works fine for me, please reopen if this is still an issue.
