### ISSUE TITLE
Low sidebar text contrast

### ISSUE THREAD

**Issue by lancelote** [FirstTimeInForever/intellij-pdf-viewer#2]
Thanks for the great plugin 👍

The only complain I have is the low sidebar text contrast with light color schemes. Darcula is great though.

<img width="767" alt="Screen Shot 2020-06-26 at 15 45 39" src="https://user-images.githubusercontent.com/2500320/85858440-4f4ada00-b7c4-11ea-81a1-afa190881b9a.png">

**Comment by FirstTimeInForever** [comment]
Thank you for the checking out my plugin!
I'll try to implement more advanced color inheritance in the next release.

**Comment by FirstTimeInForever** [comment]
Color issues should be fixed in current (v0.8) release. If you encounter some incorrect colors (e. g. sidebar icons) you can set colors you like manually in plugin settings (you will need this only for some really weird themes).
