### ISSUE TITLE
Auto-refresh not working anymore

### ISSUE THREAD

**Issue by rusudinu** [FirstTimeInForever/intellij-pdf-viewer#20]
The auto refresh function seems to not trigger on pdf content change. 

Use case:
I'm compiling latex files, and the pdf is not refreshing anymore, after the compilation is finished. Tried this on various projects, and same behavior occurs.
Latex compiler: Latexmk
If I reopen the pdf (manually) the content appears, so I think the issue is not caused by an error in Latex or Intellij.

Editor details:

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M

Plugin details:
Version: 0.10.2

**Comment by mapabe** [comment]
the same on linux
PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.21-100.fc32.x86_64

**Comment by ZhengKeli** [comment]
I fixed this problem and created a pull request #22 
Hope that helps.

**Comment by rusudinu** [comment]
Fixed in release [v0.11.0](https://github.com/FirstTimeInForever/intellij-pdf-viewer/releases/tag/v0.11.0).
