### ISSUE TITLE
dependency cycle

### ISSUE THREAD

**Issue by cbtum** [FirstTimeInForever/intellij-pdf-viewer#25]
Would love to use the build in pdf viewer together with TeXiFy which seems to be working until I restart Intellij. After restart, the following error appears in my event log:

> Plugin error: Plugins 'PDF Viewer', 'TeXiFy IDEA' cannot be loaded because they form a dependency cycle

My Setup: Intellij 2021.1, Texify 0.7.4, MacOS 10.15.7

**Comment by PHPirates** [comment]
You need to update to TeXiFy 0.7.5.
