### ISSUE TITLE
Default PDF viewer sidebar to bookmarks view

### ISSUE THREAD

**Issue by kalekje** [FirstTimeInForever/intellij-pdf-viewer#28]
I have a shortcut for toggling the PDF viewer sidebar (shift + right click), and set that same shortcut to show bookmark view.
I still have to manually click on the bookmark button for it show, however, as it defaults to thumbnail view. I think that a setting to change the default sidebar to bookmark instead of thumbnail would be useful.

**Comment by PHPirates** [comment]
Fixed in 0.12
