### ISSUE TITLE
Feature Request - Keep document position on reload

### ISSUE THREAD

**Issue by RikardLegge** [FirstTimeInForever/intellij-pdf-viewer#30]
Would it be possible to add an option to keep the PDF scroll position when reloading the document? When working with latex and regularly recompiling the source code, scrolling multiple pages after each reaload is not optimal. 

If you accept pull requests I could prepare a PR with a naive implementation which just scrolls the document back to the previous position after a reload.

**Comment by FirstTimeInForever** [comment]
It is actually already properly (hopefully) implemented in the current development version of the plugin (you can check out the `kotlinjs-migrate` branch). Unfortunately, it is taking much more time than I expected to publish the next release, as there are still some issues that should be fixed.

In the mean time, you can try out the alpha build as it should mostly work fine. You can download it from the actions page (https://github.com/FirstTimeInForever/intellij-pdf-viewer/runs/2669388506). You need to unzip `plugin-artifact.zip` and manually install inner `intellij-pdf-viewer-0.12.0-alpha.1.zip` (`Plugins` > click gear icon > `Install plugin from disk`).

I published the current development version into alpha channel in the plugin marketplace, but it will be available only in, like, a day or two.

**Comment by slideclimb** [comment]
In any case, if you are using [TeXiFy](https://github.com/Hannah-Sten/TeXiFy-IDEA) as your LaTeX plugin, you should be able to select this PDF viewer in your run configuration. Then TeXiFy should automatically open the pdf and forward search to it after you compile, and you can also inverse search from the pdf to the tex source. See the [TeXiFy wiki](https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Built-in-pdf-viewer-support) for more information.

**Comment by RikardLegge** [comment]
@FirstTimeInForever Sounds great! Only checked the issue tracker for related issues and dit not find any, will try the alpha build for the time being.

@slideclimb Am using TeXiFy and have it setup as you propose, with the exception of automatically opening the pdf. Disabling the option seems to disable forwards and backwards searching which is inoptimal but not a dealbreaker. The reason why I'm disabling this option is because I use split view, the pdf document is reopened in the same "window" as the code which defeats the purpouse of having the source code and rendered document side by side. I do not know if this is an issue with my configuration, PDF-viewer or TeXify. If I'm the only person with this problem I would suspect that it's due to my setup.

**Comment by slideclimb** [comment]
Ah, right. I had set it to open in the right split pane by default because most people use (I assume) only a single editor when editing tex. If you position the pdf viewer to be where you want it to be the first time after it automatically opens, then forward search should work fine. If it doesn't, that's probably a bug in the pdf viewer (my bad).

**Comment by leimath** [comment]
Considering the last update was yesterday (by Jetbrains versions tab) is this issue supposed to be fixed/added in the latest version (0.13.0) ? I am on the latest yet this functionality isn't available
