### ISSUE TITLE
PyCharm freeze on reverse search

### ISSUE THREAD

**Issue by PythonFZ** [FirstTimeInForever/intellij-pdf-viewer#32]
First of all, thanks for this Plugin. It is very nice to see that we now have  a PDF Viewer for the great Intellij tools.
I am using it with TeXiFy and the `ctrl + click` reverse search.

If I click on some part of the PDF that does not exist in the corresponding `*.tex` file PyCharm freezes and does not recover.
I am not sure, if this is an issue related to PDF-Viewer or TeXiFy.

I am using Windows 10 with PyCharm 2021.1.1

**Comment by slideclimb** [comment]
That sounds like a pdf viewer issue, I will have a look at it.

**Comment by slideclimb** [comment]
It might be solved in the alpha build already, could you give that a shot and report back if that solves your problem?

---

You can download the alpha build from the [JetBrains plugins repo](https://plugins.jetbrains.com/plugin/14494-pdf-viewer/versions/alpha), and then [install the plugin from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk). Or you can subscribe to the alpha channel by adding https://plugins.jetbrains.com/plugins/alpha/14494 to the list of repositories by going to **Settings | Plugins | gear icon | Manage Plugin Repositories | plus icon**.

**Comment by PythonFZ** [comment]
I had to update to PyCharm 2021.1.2 RC but I couldn't reproduce the issue! Thanks for the update instructions, I didn't know about adding the alpha channel! Keep up the good work and thanks a lot!
