### ISSUE TITLE
How to return back to PDF after an URL clicked?

### ISSUE THREAD

**Issue by khssnv** [FirstTimeInForever/intellij-pdf-viewer#38]
Hello. How can I go back to PDF after an URL clicked and a web page appears in the viewer tab? Thanks!

**Comment by PHPirates** [comment]
I don't think this is currently possible, I asked this before as well: https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/23#issuecomment-860169451 so some changes need to be made.
