### ISSUE TITLE
[0.12.0-alpha.4] Zoom out shortcut is broken.

### ISSUE THREAD

**Issue by WantToLearnJapanese** [FirstTimeInForever/intellij-pdf-viewer#43]
I am using the alpha version because of the synctex issue. (PyCharm crashed occasionally)

On this version, 0.12.0-alpha.4, the zoom-out("Decrease the document scale") shortcut is broken.

I mapped zoom-in and out with "Ctrl-scroll up" / "Ctrl-scroll down"

While zoom-in("Increase ...") works, the zoom-out shortcut only works when the mouse is on the **editor pane.**

**Comment by Bibo-Joshi** [comment]
Hi. I can reproduce this on version 0.11.1 - scroll-down will magnify unless the cursor is in the search bar :)

**Comment by PHPirates** [comment]
Works for me now, so I think this will be fixed in the next version
