### ISSUE TITLE
Feature Request: Remember PDF Sidebar visibility and selected view between refreshed documents

### ISSUE THREAD

**Issue by andrfgs** [FirstTimeInForever/intellij-pdf-viewer#44]
First of all, I'd like to thank for this amazing plugin which helps me a lot using LaTeX inside PyCharm. But there's just one feature I'd like to request, if possible.

Whenever I reload a PDF, either by clicking the refresh button or by recompiling the LaTeX document, the plugin hides the sidebar and sets it to the default thumbnails view. In my specific case, everytime I recompile the document, I have to manually select the `Bookmarks View` and also toggle the visibility of the sidebar.

Would it be possible to remember this setting between refreshes?

I am using PyCharm 2021.2.2 (Java 11.0.11) on an Arch Linux distro.

**Comment by PHPirates** [comment]
Yes, in Settings > PDF Viewer > Default sidebar view mode
