### ISSUE TITLE
Top Bar with Page Numbers and Zoom Level is not Showing.

### ISSUE THREAD

**Issue by kamal19k** [FirstTimeInForever/intellij-pdf-viewer#46]
On Windows, the bar on top of the page that shows number of pages, zoom level, and some other info, is not visible. When the page is refreshed, you can see it for a few seconds but then disappears. Is there a way to make it visible all the time?

![PDF_Viewer Bar Missing](https://user-images.githubusercontent.com/16297608/151905994-520f18d9-aee0-4ee8-811d-5e290d94d9f7.png)

**Comment by PHPirates** [comment]
This was indeed an issue in 0.11, but this has been fixed in the latest release (the extra toolbar should not show)
