### ISSUE TITLE
401 Unauthorized (only Android Studio)

### ISSUE THREAD

**Issue by igorog** [FirstTimeInForever/intellij-pdf-viewer#47]
Hello!

`Linux FIRE 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux

Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+0-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.4-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1)
Current Desktop: X-Cinnamon`

Install.... First run...
```
`JCEF is not available!
Seems like your current runtime does not provide JCEF classes. If you are sure that it does - please ensure 'ide.browser.jcef.enabled' registry property is set to true.
  
Why am I seeing this?
This plugin uses new IntelliJ platform implementation of web browser called JCEF (Java Chromium Embedded Framework). This feature is still in development, so there might be some bugs.
 
Please ensure you are:
Running IDE with JetBrains Runtime
You are using default JBR bundled with IDE
JCEF is enabled (check ide.browser.jcef.enabled registry flag - it should be enabled)`
```
"401 Unauthorized"

**Comment by slideclimb** [comment]
First off, that's a little rude and totally unnecessary. I do agree that this plugin is a great addition and that it would benefit from more active development. Feel free to contribute! :) On my end this is a hobby project, and sometimes life gets in the way of hobbies. It happens.

With that out of the way; it looks like it might be a problem on your end. I can open a pdf file perfectly fine on IntelliJ 2021.3.2 with version 0.11.1 of the plugin. Could you please check the following:

1. [Do you have JCEF enabled?](https://stackoverflow.com/a/28419108/6629569)
  i. Double <kbd>shift</kbd>
  ii. Search for `Registry...`
  iii. Scroll down until you find the `ide.browser.jcef.enabled` key and check that the checkbox next to it is enabled.
2. [Which runtime is used to run your IDE?](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)
  i. Double <kbd>shift</kbd>
  ii. Search for `Choose Boot Java Runtime for the IDE`
  iii. Check that the current runtime is a JetBrains runtime. If it is not you can select one with JCEF support from the dropdown.

**Comment by igorog** [comment]
> With that out of the way; it looks like it might be a problem on your end. I can open a pdf file perfectly fine on IntelliJ 2021.3.2 with version 0.11.1 of the plugin. Could you please check the following:
> 
> 1. [Do you have JCEF enabled?](https://stackoverflow.com/a/28419108/6629569)
>    i. Double shift
>    ii. Search for `Registry...`
>    iii. Scroll down until you find the `ide.browser.jcef.enabled` key and check that the checkbox next to it is enabled.
> 2. [Which runtime is used to run your IDE?](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)
>    i. Double shift
>    ii. Search for `Choose Boot Java Runtime for the IDE`
>    iii. Check that the current runtime is a JetBrains runtime. If it is not you can select one with JCEF support from the dropdown.

Hello! Thank you very much for your reply. Sorry for my involuntary rudeness. It happened because of not quite correct my English.
Essentially the questions:
1. ide.browser.jcef.enabled - enabled.
[<a href="https://ibb.co/86MY0MY"><img src="https://i.ibb.co/86MY0MY/ide-browser-jcef-enabled.png" alt="ide-browser-jcef-enabled" border="0"></a>](url)
2. 11.0.11 Bundled
[<a href="https://ibb.co/GdMTQdq"><img src="https://i.ibb.co/GdMTQdq/runtime.png" alt="runtime" border="0"></a>](url)

**Comment by igorog** [comment]
When I select a different runtime: the plugin interface appears, but the pdf itself is not displayed.

[<a href="https://ibb.co/XXZNZYy"><img src="https://i.ibb.co/XXZNZYy/new-runtime.png" alt="new-runtime" border="0"></a>](url)

Writes 401 Unauthorized.

[<a href="https://ibb.co/S3ctJPL"><img src="https://i.ibb.co/S3ctJPL/unautorized.png" alt="unautorized" border="0"></a>](url)

**Comment by Orienser** [comment]
I have the same issue, "401 Unauthorized", after change IDE runtime to 11.0.11+9-b1341.60-jcef

IDE: Android Studio Bumblebee | 2021.1.1 Patch 1

**Comment by slideclimb** [comment]
Sorry for my late reply. Sounds like we're getting at least a little closer to a working pdf viewer. It looks like the plugin (pdfjs) is not authorized to view your pdf. I have not been able to reproduce this locally in my IntelliJ (2021.3.2) with runtime `11.0.13.7-1751.25-jcef`. It might be an issue with Android Studio, runtime 11.0.11, or another local configuration. It's suspicious that both of you are on Android Studio 2021.1.1.

@igorog and @Orienser Where are your pdf file and your project located, and how do you open the pdf? Can you open the pdf in the same way in IntelliJ and tell me if that works? I will give Android Studio a try as well.

**Comment by Orienser** [comment]
Android Studio:

**Comment by igorog** [comment]
> Where are your pdf file and your project located, and how do you open the pdf? Can you open the pdf in the same way in IntelliJ and tell me if that works? I will give Android Studio a try as well.

Hello, @slideclimb! I have Arch Linux installed. The Android Studio projects folder is located by default along the path: ~/AndroidStudioProjects. I tried to launch a PDF file both from the project directory and from the ~/Downloads folder. The result is one - 401 Unauthorized. I even tried to install android studio on Windows, but even there the plugin also gives a launch error (401) for pdf documents.
Until recently I couldn't run PDF even on Stable IntelliJ Idea. But after I reinstalled Idea on the Canary channel, the pdf files started to run without problems.

**Comment by Orienser** [comment]
With Android Studio 2021.1.1 (runtime: 11.0.11.9-1341.60-jcef) on Windows, both of the following ways are 401 Unauthorized.
1. PDF file from desktop (`C:\Users\{USERNAME}\Desktop`), project from `D:\Android\AndroidStudioProjects`.
2. PDF file and project both from same folder `D:\Android\AndroidStudioProjects`. 
<br>
With IDEA 2021.3.2 (runtime: 11.0.13.7-1751.25-jcef) on Windows, the pdf file can be opened correctly.

**Comment by slideclimb** [comment]
So it seems like an Android Studio problem indeed. I'll look into it.

As for JCEF not being available in Android Studio by default, it's a [known issue](https://issuetracker.google.com/issues/159933628?pli=1) that the [AsciiDoc Plugin](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#choose-jdk) had/has to deal with as well.

**Comment by slideclimb** [comment]
To get back to this: when opening the console in AS (right click on the PDF > `open dev tools`) I see a lot of error messages:

```
Uncaught ReferenceError: triggerMessageEvent is not defined
    at <anonymous>:1:1
```

I'm not at all familiar with the current KotlinJS/JavaScript side of things. @FirstTimeInForever Can you investigate this further?

**Comment by igorog** [comment]
Agree, it's a little strange to release new versions of plugin for the EAP. In view of this, I cannot check this fix for Android Studio.
Earlier, of course, I installed Android Studio EAP release, but due to unstable work, I again rolled back to a stable release.

**Comment by bsshor** [comment]
> First off, that's a little rude and totally unnecessary. I do agree that this plugin is a great addition and that it would benefit from more active development. Feel free to contribute! :) On my end this is a hobby project, and sometimes life gets in the way of hobbies. It happens.
> 
> With that out of the way; it looks like it might be a problem on your end. I can open a pdf file perfectly fine on IntelliJ 2021.3.2 with version 0.11.1 of the plugin. Could you please check the following:
> 
> 1. [Do you have JCEF enabled?](https://stackoverflow.com/a/28419108/6629569)
>    i. Double shift
>    ii. Search for `Registry...`
>    iii. Scroll down until you find the `ide.browser.jcef.enabled` key and check that the checkbox next to it is enabled.
> 2. [Which runtime is used to run your IDE?](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)
>    i. Double shift
>    ii. Search for `Choose Boot Java Runtime for the IDE`
>    iii. Check that the current runtime is a JetBrains runtime. If it is not you can select one with JCEF support from the dropdown.

yeah，through your ways，I can open the PDF.

**Comment by PHPirates** [comment]
This is working for me with PDF Viewer 0.14. I do have to select a JBR with JCEF enabled in the "Choose Boot Java Runtime" dialog as described above.
