### ISSUE TITLE
Scrolling by macOS touchpad is laggy

### ISSUE THREAD

**Issue by Him188** [FirstTimeInForever/intellij-pdf-viewer#51]
The view responds slowly when I scroll. It takes a few more seconds to complete its scrolling after I leave my finger off the touchpad.

**Comment by PHPirates** [comment]
I do not experience anything like that, does it happen with other (small) pdfs as well? Also after restarting the OS and just opening a pdf?

**Comment by Him188** [comment]
Yes, it happens with small (2-page) pdfs. Restarting IDE and OS doesn't help. Even the thumbnail sidebar is also slow.

**Comment by FirstTimeInForever** [comment]
@Him188 Is it just slow or laggy? Please try scrolling document preview in bundled Markdown plugin. Is it slow too?
Please try increasing the value of `ide.browser.jcef.osr.wheelRotation.factor` registry key (`Search Everythere > Registry...`).

**Comment by Him188** [comment]
It's slow and laggy.
https://user-images.githubusercontent.com/12100985/168280893-ed4edc03-f432-4069-8863-b47ae678aa82.mp4

There is no problem scrolling preview in bundled Markdown plugin. 
I tried increasing the registry from 10 to 20, it is not slow but is still laggy.

**Comment by ThijmenDam** [comment]
Can confirm the problem (2016 MBP).

**Comment by alexgunsberg** [comment]
Can confirm the problem (MacBook Pro M1 Max, macOS 12.5.1)

**Comment by abmummaneni** [comment]
Can also confirm (MacBook Pro M1 Pro macOS 12.5.1)

**Comment by MaxSchambach** [comment]
Having the same issue (MacBook Pro M1 Pro, macOS 12.5)

**Comment by numpee** [comment]
Same issue here (MacBook Pro M1 Pro, macOS 12.3)

**Comment by ClementGre** [comment]
I have the same issue (MacBook Pro M1, macOS 12.6)

**Comment by fabian-kho** [comment]
I have the same issue (MacBook Pro M1 Pro, macOS 12.6)

**Comment by Darcy382** [comment]
I have the same issue (MacBook Pro M1 Max, macOS 13.0

**Comment by ahar0n** [comment]
I have the same issue (MacBook Pro M1 Pro, macOS 13.0.1)

**Comment by theqihao** [comment]
I have the same issue (Mac Mini 2020, macOS 12.5.1)

**Comment by mikepziegler** [comment]
Same Issue here (Macbook pro 16'' 2019, macOS 12.6)

**Comment by tasbouz** [comment]
I have the same issue (MacBook Air M1 2020, macOS 13.1)

**Comment by beenbiishop** [comment]
I also have this issue (MacBook Pro M1 Pro, macOS 13.1, IntelliJ 2022.3.1 (Ultimate))

**Comment by philipLutz** [comment]
I also have this issue (2021 MacBook Pro M1 Max, 32GB, macOS 13.0, CLion 2022.3).

**Comment by IamM47Z** [comment]
I also have this issue (2020 MacBook Air M1, 8GB, macOS 13.2.1, IntelliJ 2022.3.2).

**Comment by tanjuntao** [comment]
I got the same issue (2020 MacBook Pro Intel, macOS 13.2.1, PyCharm 2022.2 Professional Edition). 

Is this issue solved now?

**Comment by Arlaz** [comment]
I also have this issue (2021 MacBook Pro M1 Max, 64GB, macOS 13.3, PyCharm 2023.1 Professional Edition).

**Comment by Alacho2** [comment]
I also have this issue. MBP 2019, i9, 32GB, MacOS 13.2.1, 5500M 4gb, WebStorm and Clion.

**Comment by Him188** [comment]
I found a workaround:

- Double shift, type "Registry" and open
- Enable "ide.browser.jcef.contextMenu.devTools.enabled"
- Now the viewer is not laggy

But you have to keep the devTools window open.

@FirstTimeInForever Any thoughts? I tried investigating this problem but I failed to find the cause.

**Comment by aeropagz** [comment]
when is this change released?

**Comment by aeropagz** [comment]
ah great, thnx a lot, now its working like a charm !

**Comment by theqihao** [comment]
> With [ad34116](https://github.com/FirstTimeInForever/intellij-pdf-viewer/commit/ad34116b4d37100700f15cdc7a6389c3bbb4602a), scrolling is not laggy anymore. Fantastic!
> 
> @aeropagz I built a plugin from the master branch. You can drag this into your IDE to install. You can also build your own, it's quite simple: `./gradlew buildPlugin`, and find it at `plugin/build/distributions`
> 
> [intellij-pdf-viewer-0.14.3.zip](https://github.com/FirstTimeInForever/intellij-pdf-viewer/files/11442245/intellij-pdf-viewer-0.14.3.zip)

Nice, it works!

**Comment by PHPirates** [comment]
That's great to hear, thanks for checking! We will publish a new release to the marketplace soon.
