### ISSUE TITLE
Code with me support

### ISSUE THREAD

**Issue by justanhduc** [FirstTimeInForever/intellij-pdf-viewer#52]
Hi @FirstTimeInForever. Thanks a lot for this amazing plugin. Currently, I wanna use Pycharm to replace Overleaf when collaborating on paper. But the problem is PDF viewer currently does not work in Intellij Code with me editor yet, so I cannot see the PDF in the client side. Do you have any timeline to support this functionality?

**Comment by PHPirates** [comment]
I can confirm the issue. Installing the pdf viewer in the client did not help.

![image](https://user-images.githubusercontent.com/15669080/236277314-a816eaff-f0c7-4182-bd7a-902ace95881c.png)

**Comment by liudongmiao** [comment]
@PHPirates very strange issue.

When the Code with me client open the pdf, it cannot show.
Then install the plugin (latest build), the pdf can be open.
After, it cannot be open again.

The url is cwm:// link, it's supported in virtual file system.

**Comment by PHPirates** [comment]
I can still reproduce the issue as well, but not sure how to fix it. Markdown preview works fine so it may not be a jcef issue.

**Comment by liudongmiao** [comment]
@PHPirates please report to idea client (code with me).

1. if code with me host install the pdf plugin, and client don't install
Then, a opened pdf file can be refreshed by a fresh install, the virtual file is cwm://xxx

2. if code with me host don't install the pdf plugin, client cannot open pdf files

3. if code with me host and client both installed the pdf plugin, client cannot open
And the `accept` method is never called by idea client

**Comment by liudongmiao** [comment]
upstream bug: https://youtrack.jetbrains.com/issue/CWM-1199

**Comment by liudongmiao** [comment]
similar: https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/994

**Comment by liudongmiao** [comment]
@PHPirates  After decompiled markdown plugin in code with me client, now we can support code with me too.

**Comment by liudongmiao** [comment]
However, IMO, this shouldn't be labed as `bug`, `enhancement` should be a better label.
