### ISSUE TITLE
Cannot remove the sidebar

### ISSUE THREAD

**Issue by Volume999** [FirstTimeInForever/intellij-pdf-viewer#56]
I cannot remove the sidebar and it takes 1/6th of the screen. Pressing "hide sidebar" does not work. Error is on Mac M1

**Comment by kelleyrw** [comment]
I can verify I have the same issue on an M1 mac.

**Comment by kelleyrw** [comment]
I can confirm that uninstalling/reinstalling the plugin seemed to resolve the issue.

**Comment by jlous** [comment]
I have the same problem but specifically: I can only change the sidebar setting once.
If I close all pdfs and open one, it opens with sidebar
If I select "hide sidebar" it works
If I try to turn it on again, nothing happens.
If I open an additional pdf, it opens with sidebar visible, but its "hide sidebar" option is checked and unresponsive.

**Comment by Mattwmaster58** [comment]
This only happens to me when I have > 1 PDF open at once, otherwise it works fine.
