### ISSUE TITLE
pdf viewer gets blank while editing Latex

### ISSUE THREAD

**Issue by Stype0912** [FirstTimeInForever/intellij-pdf-viewer#77]
My pdf viewer usually gets dark and need to press the refresh button to show again. The bug does not recur steadily. Here is the [screen recording link](https://drive.google.com/file/d/1ipeAWYc9nOhRK0FY9Tf7Eh-8dTG2jeY7/view?usp=sharing).

**Comment by PHPirates** [comment]
This could be the same as #37, but not sure. Could you try to install the following build (yet to be released) and see if it is fixed? 
[intellij-pdf-viewer-0.14.3-3.zip](https://github.com/FirstTimeInForever/intellij-pdf-viewer/files/11480923/intellij-pdf-viewer-0.14.3-3.zip)

**Comment by Stype0912** [comment]
It works !!
