### ISSUE TITLE
Files on Remote Host cannot be shown

### ISSUE THREAD

**Issue by johan12345** [FirstTimeInForever/intellij-pdf-viewer#81]
I use a remote interpreter (on an SSH host) in PyCharm and use "Tools -> Deployment -> Browse Remote Host" to look at outputs generated by my code running on the remote host. Unfortunately the PDF Viewer plugin doesn't seem to be able to display PDF files on the remote host. I get the error messages like this:

```
PDF.js v2.6.347 (build: 3be9c65f)
Message: Missing PDF "http://localhost:63342/64fa8636-e686-4c63-9956-132d9471ce77/get-file/%3C53c2adbd-d399-4b8f-a63b-b881a65c13b9%3E/tmp/pycharm_project_288/outputs/my_output.pdf".
```

Not sure if this is the same underlying issue as #29, but it is a different situation as there are no special characters in the path (at least not in the path on the remote host itself, i.e. `/tmp/pycharm_project_288/outputs/my_output.pdf`).

**Comment by The193thDoctor** [comment]
Hi, I am having similar issues. I cannot open .pdf even with the plugin installed on gateway remote machine on ssh.
