### ISSUE TITLE
Support for simple dark mode

### ISSUE THREAD

**Issue by subasharyalgeorgian** [FirstTimeInForever/intellij-pdf-viewer#82]
Can we have the feature where we can just change the page background to black and text to white ?

**Comment by slideclimb** [comment]
This was added in #73, so please update to [0.15.0](https://plugins.jetbrains.com/plugin/14494-pdf-viewer/versions/stable/344682) where this should be available by going to **Settings > PDF Viewer > Document Colors**

**Comment by PHPirates** [comment]
@slideclimb Doesn't that invert all colors? The issue here is to only invert black and white, and keep other colors the same
