### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no chrome_elf in java.library.path: D:\softWare\pycharm\PyCharm 2023

### ISSUE THREAD

**Issue by Coder-Ben** [FirstTimeInForever/intellij-pdf-viewer#83]
who can help me,i dont know whats happened

**Comment by PHPirates** [comment]
Well, I don't know either, but I would think these kind of dependencies would be distributed together with IntelliJ. Do you have any kind of nonstandard installation? You could try to reinstall.
What version of IntelliJ and what version of the pdf viewer are you using?
