### ISSUE TITLE
Multiple Monitor Display Issue on Mac

### ISSUE THREAD

**Issue by callumjohnspiller** [FirstTimeInForever/intellij-pdf-viewer#85]
I am using the latest version of the plugin on IntelliJ IDEA 2023.1.4 (Ultimate Edition). This is with MacOS 13.4.1 (22F82)

When I have the editor open on one monitor, and the .pdf viewer on another in a separate window, when I make a change in the editor, the pdf disappears from view in the pdf viewer. The .pdf only comes back into view when I click on or focus on the pdf viewer window.

**Comment by PHPirates** [comment]
What do you mean exactly with 'make a change in the editor' and 'disappears from view'? Could you provide a screenshot?
Do I understand correctly this only happens with the pdf viewer is in a separate window on a separate monitor?

**Comment by PHPirates** [comment]
Many thanks for the video! That looks very much like a rendering issue on Mac, not a plugin issue (I don't see this on Windows/Linux). It might be you are running into some version of this issue: https://youtrack.jetbrains.com/issue/JBR-4897/Reconnecting-multiscreen-monitor-displays-blank-IDE
If you want to be sure, you could create a youtrack issue as well.
