### ISSUE TITLE
[feature request] save sidebar state and others

### ISSUE THREAD

**Issue by Mattwmaster58** [FirstTimeInForever/intellij-pdf-viewer#89]
I rarely like the sidebar open, I find myself having to close it every launch. I would personally find it useful to save this option either per-project, document, or globally.

**Comment by PHPirates** [comment]
Of course, you can change this in File > Settings > PDF Viewer > Default sidebar view mode=Closed

![image](https://github.com/FirstTimeInForever/intellij-pdf-viewer/assets/15669080/518bbbc3-387c-4c7b-839a-f2213a1b0be9)
