### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by olegogogo** [FirstTimeInForever/intellij-pdf-viewer#97]
I have created new clear LaTeX project with TeXify plagin and just run main.tex file. As a result i got next message in console:
```
pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-directory=D:/Innopolis/untitled1/out main.tex

Process finished with exit code -1073741515 (0xC0000135)
```
This log says nothing to me, so maybe there is someone who knows how to deal with it?

**Comment by PHPirates** [comment]
Indeed, something must have been seriously broken in your latex installation. However, it has nothing to do with the pdf viewer plugin, for general latex questions you can use sites like https://tex.stackexchange.com
