### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by TomtheCoder2** [FirstTimeInForever/intellij-pdf-viewer#99]
The zoom function (+/- buttons and ctrl + scroll) doesnt work in the pdf presention mode

**Comment by PHPirates** [comment]
As I understood, pdf presentation mode is just to get your whole page (a slide) fit into view? So if you want to zoom, why use presentation mode?

**Comment by TomtheCoder2** [comment]
im using it because i want to hide the sidebar, because on small screens it just wastes space when working in split screen mode

**Comment by PHPirates** [comment]
![image](https://github.com/FirstTimeInForever/intellij-pdf-viewer/assets/15669080/678f22a8-f887-486e-b9ad-f2d0e3c90cf7)

Which sidebar?


Or do you mean this one, discussed in #95 which can be closed if you are using either intellij 2023.3 or earlier or plugin version 0.16 from #98 

![image](https://github.com/FirstTimeInForever/intellij-pdf-viewer/assets/15669080/5414c973-3640-4d22-ba38-8bc444235104)

**Comment by TomtheCoder2** [comment]
yes i meant this one. if you're already aware of the issue (not being able to hide the side bar) you could close this issue too, if you think the ability to zoom is not necessary in the presentation mode. I'm just using the presentation mode as it is currently the only way to hide the sidebar

**Comment by PHPirates** [comment]
Thanks, yes you could also install the plugin from the zip I linked in #98. We will try to get out a new release soon to fix the issue
